### ISSUE TITLE
Number of leds

### ISSUE THREAD

**Issue by rsurya07** [dylanzodrow/Aerial_Drone_Tracking#13]
Would it be better if we doubled or tripled the leds to get a more accurate output? We've 8 leds with 45 degrees in between. That feels like to0 much to be accurate. We can use a mux to turn on the leds using 4 or 5 gpio pins.

**Comment by GaryLazerFinz** [comment]
We have 24 leds. They are controlled with 6 gpio pins

**Comment by rsurya07** [comment]
But I thought only 8 were used for direction and each mic has two other leds that corresponds to height

**Comment by GaryLazerFinz** [comment]
i would say each mic has three leds. the direction is indicated by the leds
being on and the  height is indicated by one to three leds being lit.

**Comment by GaryLazerFinz** [comment]
I have the LEDs ready to go . Lets Test Them.

**Comment by GaryLazerFinz** [comment]
Works with the Signal Generator
