### ISSUE TITLE
Design Microphone Array

### ISSUE THREAD

**Issue by dylanzodrow** [dylanzodrow/Aerial_Drone_Tracking#5]
Design the microphone array for the measured frequency spectrum. Microphones should be spaced for wavelengths of interest.

**Comment by GaryLazerFinz** [comment]
I have a KiKad started. It is not complete yet. We need to know the proper distance. Now I am thinking 8kHz is the largest frequency we need to capture. I am not really sure what connector would be the best solution.

**Comment by GaryLazerFinz** [comment]
The Mic Array is designed we just need to get the break out boards tested. Then make eight more in the oven in one run. Then attach them to the array shield. .
